version: "2"

services:
  node:
    build: .
    image: ts
    working_dir: /usr/src/app
    environment:
        - NODE_ENV=development #development #production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    #command: bash -c "npm install" # the first run
    command: bash -c "npm run start"